// USER REDUCERS
export const SET_AUTHENTICATED = "SET_AUTHENTICATED";
export const SET_UNAUTHENTICATED = "SET_UNAUTHENTICATED";
export const SET_ADMIN_AUTHENTICATED = "SET_ADMIN_AUTHENTICATED";
export const SET_USER = "SET_USER";
export const LOADING_USER = "LOADING_USER";

// UI REDUCERS
export const SET_ERRORS = "SET_ERRORS"
export const SET_ERRORSTATE = "SET_ERRORSTATE"
export const LOADING_UI = "LOADING_UI"
export const CLEAR_ERRORS = "CLEAR_ERRORS"
export const UNSET_ERRORSTATE = "UNSET_ERRORSTATE"
export const UNLOADING_UI = "UNLOADING_UI"

//DATA REDUCERS